# SITE CONFIGURATION
baseurl: ""
url: "https://tma995.github.io/"

excerpt_separator: "<!-- more -->"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Tim's Blog
  avatar: assets/img/face0.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Welcome to Tianxiang Ma's GitHub Pages.</p>
  header_text_feature_image: 
  footer_text: >
   Copyright <a href="https://github.com/tma995/tma995.github.io">2018</a>

  # Icons
  rss: false
  email_address: "tma995@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "matianxiang"
  flickr:
  gitlab:
  github: "tma995"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/matianxiang/" 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-138342222-1"
  disqus_shortname: "tma995"
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
